# Generated by Django 3.1 on 2020-08-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0003_auto_20200830_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='publish_date',
            field=models.DateField(verbose_name='Published'),
        ),
    ]
