# Generated by Django 3.1 on 2020-08-30 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0004_auto_20200830_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='image',
            name='publish_date',
        ),
    ]
