# Generated by Django 3.1 on 2020-08-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0005_auto_20200830_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
