# Generated by Django 3.1 on 2020-08-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0007_auto_20200830_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='question_text',
        ),
        migrations.AddField(
            model_name='pictures',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%D/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='image_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
