# Generated by Django 3.1 on 2020-08-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0008_auto_20200830_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%D/%m/%Y/')),
                ('image_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
