# Generated by Django 3.1 on 2020-08-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0009_auto_20200830_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/2020/8/30'),
        ),
    ]
