# Generated by Django 3.1 on 2020-08-31 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0010_auto_20200830_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_published',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 30), null=True),
        ),
    ]
