# Generated by Django 3.1 on 2020-08-31 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0011_auto_20200830_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_published',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
