# Generated by Django 3.1 on 2020-09-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0012_auto_20200830_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/2020/9/1'),
        ),
    ]
