# Generated by Django 3.1 on 2020-09-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0013_auto_20200901_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/2020/9/4'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/2020/9/4'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/2020/9/4'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/2020/9/4'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/2020/9/4'),
        ),
        migrations.AddField(
            model_name='image',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
