# Generated by Django 3.1 on 2020-09-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0014_auto_20200904_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_5',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/2020/9/7'),
        ),
    ]
