# Generated by Django 3.1 on 2020-09-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0015_auto_20200907_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/2020/9/9'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/2020/9/9'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/2020/9/9'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/2020/9/9'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/2020/9/9'),
        ),
    ]
