# Generated by Django 3.1 on 2020-09-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_rep', '0016_auto_20200909_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='total',
        ),
    ]
